name: '[Auto] Sync Fork'

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0

      - run: git remote add upstream https://github.com/crabtalk/bezel.git
      - run: git pull -f upstream main
      - run: git push -f

      - name: Update GPUI dependencies
        run: |
          perl -0pi -e          's/^gpui\s*=.+$/gpui          = { git = "https:\/\/github.com\/crabtalk\/zed", version = ">=0.2.2" }/m' Cargo.toml
          perl -0pi -e 's/^gpui_platform\s*=.+$/gpui_platform = { git = "https:\/\/github.com\/crabtalk\/zed", version = ">=0.1.0", features = [/m' Cargo.toml
          perl -0pi -e      's/^gpui_web\s*=.+$/gpui_web      = { git = "https:\/\/github.com\/crabtalk\/zed", version = ">=0.1.0" }/m' Cargo.toml

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1  # v8.1.1
        with:
          title: "[bot] Update GPUI dependencies"
          branch: bot/update-gpui-dependencies
          delete-branch: true
